# Generated by Django 5.2.13 on 2026-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
